package events

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/hishamkaram/codex-agent-sdk-go/internal/jsonrpc"
)

// dispatch_oracle_test.go is the behavior-equivalence oracle (golden master)
// guarding the ParseEvent / ParseItem dispatch refactor that replaces the
// hand-written switch statements with lookup tables.
//
// The refactor's failure class is a DROPPED or MIS-KEYED case: a method that
// silently falls through to UnknownEvent, or a method wired to the wrong
// handler. Capturing only the Go type name would miss a mis-binding inside the
// flat-delta family (item/agentMessage/delta, item/plan/delta, … all produce
// *types.ItemUpdated, distinguished only by the inner ItemDelta). So the
// signature for each corpus entry is the concrete Go type name PLUS the
// json.Marshal of the parsed result (or the error string) — a mis-binding
// changes the marshaled bytes even when the outer type matches.
//
// The golden file is regenerated by setting UPDATE_DISPATCH_ORACLE=1. It is
// committed and asserted byte-identical on every run; the dispatch refactor is
// allowed only while this test stays green.

// eventCorpus enumerates every wire method handled by ParseEvent's switch
// (parser.go), each with a deterministic, fixed params payload. Characterization
// captures whatever the current code does for each — success OR error.
var eventCorpus = []struct {
	method string
	params string
}{
	// --- Thread lifecycle ---
	{"thread/started", `{"thread":{"id":"t1"}}`},
	{"thread/archived", `{"threadId":"t1"}`},
	{"thread/unarchived", `{"threadId":"t1"}`},
	{"thread/closed", `{"threadId":"t1"}`},
	{"thread/name/updated", `{"threadId":"t1","name":"My Thread"}`},
	{"thread/status/changed", `{"threadId":"t1","status":"active"}`},
	{"thread/settings/updated", `{"threadId":"t1","settings":{"model":"gpt-5"}}`},
	{"thread/compacted", `{"threadId":"t1","tokens_freed":42,"strategy":"summarize"}`},
	{"compaction_event", `{"threadId":"t1","tokens_freed":42,"strategy":"summarize"}`},
	{"thread/tokenUsage/updated", `{"threadId":"t1","usage":{"input_tokens":10,"output_tokens":5}}`},
	{"thread/goal/updated", `{"threadId":"t1","goal":"finish the task"}`},
	{"thread/goal/cleared", `{"threadId":"t1"}`},

	// --- Turn ---
	{"turn/started", `{"threadId":"t1","turnId":"u1"}`},
	{"turn/completed", `{"threadId":"t1","turn":{"id":"u1"}}`},
	{"turn/failed", `{"threadId":"t1","turnId":"u1","error":{"message":"boom"}}`},
	{"turn/diff/updated", `{"threadId":"t1","turnId":"u1","diff":"---\n+++"}`},
	{"turn/plan/updated", `{"threadId":"t1","turnId":"u1","plan":[]}`},
	{"turn/moderationMetadata", `{"threadId":"t1","turnId":"u1"}`},

	// --- Items ---
	{"item/started", `{"threadId":"t1","item":{"type":"agentMessage","id":"m1","text":""}}`},
	{"item/updated", `{"threadId":"t1","delta":{"type":"agent_message_delta","text_chunk":"hi"}}`},
	{"item/completed", `{"threadId":"t1","item":{"type":"agentMessage","id":"m1","text":"done"}}`},

	// --- Items: streaming deltas ---
	{"item/agentMessage/delta", `{"threadId":"t1","itemId":"m1","delta":"chunk"}`},
	{"item/commandExecution/outputDelta", `{"threadId":"t1","itemId":"c1","delta":"out"}`},
	{"item/fileChange/outputDelta", `{"threadId":"t1","itemId":"f1","delta":"diff"}`},
	{"item/fileChange/patchUpdated", `{"threadId":"t1","itemId":"f1","unifiedDiff":"---"}`},
	{"item/plan/delta", `{"threadId":"t1","itemId":"p1","delta":"step"}`},
	{"item/reasoning/textDelta", `{"threadId":"t1","itemId":"r1","delta":"think"}`},
	{"item/reasoning/summaryTextDelta", `{"threadId":"t1","itemId":"r1","delta":"sum"}`},
	{"item/reasoning/summaryPartAdded", `{"threadId":"t1","itemId":"r1","summaryIndex":0}`},
	{"item/mcpToolCall/progress", `{"threadId":"t1","itemId":"mc1"}`},
	{"item/commandExecution/terminalInteraction", `{"threadId":"t1","itemId":"c1"}`},

	// --- Items: guardian auto-approval review ---
	{"item/autoApprovalReview/started", `{"threadId":"t1","itemId":"a1"}`},
	{"item/autoApprovalReview/completed", `{"threadId":"t1","itemId":"a1"}`},

	// --- Realtime (voice) ---
	{"thread/realtime/started", `{"threadId":"t1"}`},
	{"thread/realtime/closed", `{"threadId":"t1"}`},
	{"thread/realtime/error", `{"threadId":"t1"}`},
	{"thread/realtime/itemAdded", `{"threadId":"t1"}`},
	{"thread/realtime/outputAudio/delta", `{"threadId":"t1"}`},
	{"thread/realtime/sdp", `{"threadId":"t1"}`},
	{"thread/realtime/transcript/delta", `{"threadId":"t1"}`},
	{"thread/realtime/transcript/done", `{"threadId":"t1"}`},

	// --- MCP ---
	{"mcpServer/startupStatus/updated", `{"server":"docs","status":"ready"}`},
	{"mcpServer/oauthLogin/completed", `{"server":"docs"}`},

	// --- Account + model ---
	{"account/login/completed", `{"accountId":"acc1"}`},
	{"account/rateLimits/updated", `{}`},
	{"account/updated", `{"accountId":"acc1"}`},
	{"model/rerouted", `{"from":"gpt-5","to":"gpt-5-mini"}`},
	{"model/verification", `{"model":"gpt-5"}`},

	// --- System / filesystem / apps ---
	{"command/exec/outputDelta", `{"delta":"out"}`},
	{"process/outputDelta", `{"delta":"out"}`},
	{"process/exited", `{"exitCode":0}`},
	{"remoteControl/status/changed", `{"status":"connected"}`},
	{"externalAgentConfig/import/completed", `{"name":"cfg"}`},
	{"configWarning", `{"message":"deprecated key"}`},
	{"warning", `{"message":"heads up"}`},
	{"guardianWarning", `{"message":"risky"}`},
	{"deprecationNotice", `{"message":"will be removed"}`},
	{"fs/changed", `{"paths":["/a"]}`},
	{"skills/changed", `{}`},
	{"app/list/updated", `{"apps":[]}`},
	{"serverRequest/resolved", `{"requestId":"rq1"}`},

	// --- Windows platform ---
	{"windows/worldWritableWarning", `{"path":"C:\\x"}`},
	{"windowsSandbox/setupCompleted", `{}`},

	// --- Fuzzy file search ---
	{"fuzzyFileSearch/sessionUpdated", `{"sessionId":"s1"}`},
	{"fuzzyFileSearch/sessionCompleted", `{"sessionId":"s1"}`},

	// --- Hooks ---
	{"hook/started", `{"threadId":"t1","hookName":"pre"}`},
	{"hook/completed", `{"threadId":"t1","hookName":"pre"}`},

	// --- Errors ---
	{"error", `{"message":"fatal","code":"E1"}`},

	// --- default / unknown ---
	{"totally/unknown/method", `{"threadId":"t1","turnId":"u1","itemId":"i1"}`},
}

// itemCorpus enumerates every discriminator handled by ParseItem (items.go).
var itemCorpus = []string{
	`{"type":"agentMessage","id":"m1","text":"hi","phase":"final_answer"}`,
	`{"type":"userMessage","id":"u1","content":[{"type":"text","text":"hi"}]}`,
	`{"type":"commandExecution","id":"c1","command":"ls","cwd":"/","status":"success","exitCode":0}`,
	`{"type":"fileChange","id":"f1","status":"success","changes":[{"path":"/a","operation":"modify","diff":"-"}]}`,
	`{"type":"mcpToolCall","id":"mc1","server":"docs","tool":"search","arguments":{"q":"x"},"status":"success"}`,
	`{"type":"webSearch","id":"ws1","query":"go","action":{"kind":"search"}}`,
	`{"type":"memoryRead","id":"mr1","query":"k","result":"v"}`,
	`{"type":"memoryWrite","id":"mw1","key":"k","value":"v"}`,
	`{"type":"plan","id":"p1","text":"step","status":"active"}`,
	`{"type":"reasoning","id":"r1","summary":["s"],"content":["c"]}`,
	`{"type":"systemError","id":"e1","message":"boom"}`,
	`{"type":"hookPrompt","id":"hp1","fragments":[{"a":1}]}`,
	`{"type":"dynamicToolCall","id":"dt1","tool":"web","arguments":{},"status":"inProgress"}`,
	`{"type":"collabAgentToolCall","id":"ct1","tool":"Task","status":"inProgress","agentsStates":[],"senderThreadId":"s","receiverThreadIds":[]}`,
	`{"type":"imageView","id":"iv1","path":"/a.png"}`,
	`{"type":"imageGeneration","id":"ig1","status":"completed","savedPath":"/o.png"}`,
	`{"type":"enteredReviewMode","id":"er1","review":{"mode":"diff"}}`,
	`{"type":"exitedReviewMode","id":"ex1","review":{"mode":"diff"}}`,
	`{"type":"contextCompaction","id":"cc1"}`,
	`{"type":"futureUnknownType","brand":"new"}`,
	`{"not":"discriminated"}`,
}

// signature renders a parsed result + error into a deterministic golden line.
func signature(v any, err error) string {
	if err != nil {
		return fmt.Sprintf("ERR: %s", err.Error())
	}
	b, mErr := json.Marshal(v)
	if mErr != nil {
		return fmt.Sprintf("MARSHAL-ERR: %s", mErr.Error())
	}
	return fmt.Sprintf("%T | %s", v, string(b))
}

func computeDispatchGolden(t *testing.T) map[string]string {
	t.Helper()
	golden := make(map[string]string, len(eventCorpus)+len(itemCorpus))
	for _, e := range eventCorpus {
		ev, err := ParseEvent(jsonrpc.Notification{
			Method: e.method,
			Params: json.RawMessage(e.params),
		})
		golden["event:"+e.method] = signature(ev, err)
	}
	for i, raw := range itemCorpus {
		it, err := ParseItem(json.RawMessage(raw))
		golden[fmt.Sprintf("item:%02d", i)] = signature(it, err)
	}
	return golden
}

// TestDispatchOracle pins ParseEvent and ParseItem dispatch behavior against a
// committed golden file. Regenerate with UPDATE_DISPATCH_ORACLE=1.
func TestDispatchOracle(t *testing.T) {
	t.Parallel()

	goldenPath := filepath.Join("testdata", "dispatch_oracle.golden.json")
	got := computeDispatchGolden(t)

	if os.Getenv("UPDATE_DISPATCH_ORACLE") == "1" {
		// Deterministic, sorted, indented for a reviewable diff.
		keys := make([]string, 0, len(got))
		for k := range got {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		ordered := make([][2]string, 0, len(keys))
		for _, k := range keys {
			ordered = append(ordered, [2]string{k, got[k]})
		}
		buf, err := json.MarshalIndent(ordered, "", "  ")
		if err != nil {
			t.Fatalf("marshal golden: %v", err)
		}
		if err := os.WriteFile(goldenPath, append(buf, '\n'), 0o600); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("updated golden: %s (%d entries)", goldenPath, len(got))
		return
	}

	data, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden (regenerate with UPDATE_DISPATCH_ORACLE=1): %v", err)
	}
	var ordered [][2]string
	if err := json.Unmarshal(data, &ordered); err != nil {
		t.Fatalf("unmarshal golden: %v", err)
	}
	want := make(map[string]string, len(ordered))
	for _, kv := range ordered {
		want[kv[0]] = kv[1]
	}

	// Every golden key must be reproduced byte-identically.
	for k, wantSig := range want {
		gotSig, ok := got[k]
		if !ok {
			t.Errorf("dispatch case %q present in golden but missing from current run", k)
			continue
		}
		if gotSig != wantSig {
			t.Errorf("dispatch drift for %q:\n  want: %s\n  got:  %s", k, wantSig, gotSig)
		}
	}
	// No new/unexpected keys (corpus stayed in sync).
	for k := range got {
		if _, ok := want[k]; !ok {
			t.Errorf("dispatch case %q present in current run but missing from golden", k)
		}
	}
}
